# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'componentes_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_cb = QtWidgets.QFrame(self.centralwidget)
        self.logo_cb.setGeometry(QtCore.QRect(70, 300, 572, 160))
        self.logo_cb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_cb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_cb.setObjectName("logo_cb")
        #self.logo_cb.setStyleSheet("backgroung-image: url(C:\Users\LENOVO\OneDrive - Universidad del rosario\Escritorio\Final_Final_DABM_Monitor_Temperatura\logocbmt.jpg);")
        self.logo_cb.setStyleSheet("background-image: url(logocbmt.jpg);")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 10, 201, 22))
        self.comboBox.setObjectName("comboBox")

        f = open("opciones.csv", "r")
        opciones = f.readlines()
        for op in opciones:
            self.comboBox.addItem(op)

        f.close()

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 50, 201, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        # PARA PUSH BUTTON 1:
        #self.pushButton_3.clicked.connect(self.veropcion1)



        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 190, 381, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 151, 121))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(430, 50, 231, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 280, 90, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 280, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        self.menuParametros = QtWidgets.QMenu(self.menubar)
        self.menuParametros.setObjectName("menuParametros")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuInicio.menuAction())
        self.menubar.addAction(self.menuParametros.menuAction())

        self.pushButton.clicked.connect(self.ver_opcion_1)
        self.pushButton_3.clicked.connect(self.leer_usuarios)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_2.setText(_translate("MainWindow", "Masculino"))
        self.radioButton_3.setText(_translate("MainWindow", "Femenino"))
        self.radioButton.setText(_translate("MainWindow", "Prefiero No Decirlo"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_3.setText(_translate("MainWindow", "Hipertensión"))
        self.checkBox_2.setText(_translate("MainWindow", "Diabetes"))
        self.checkBox.setText(_translate("MainWindow", "Fracturas"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.menuInicio.setTitle(_translate("MainWindow", "Inicio"))
        self.menuParametros.setTitle(_translate("MainWindow", "Parametros"))

    def ver_opcion_1(self):
        # para los radiobuttons
        if (self.radioButton.isChecked()):
            print("Seleccionaste: ", self.radioButton.text())
        elif (self.radioButton_2.isChecked()):
            print("Seleccionaste: ", self.radioButton_2.text())
        elif (self.radioButton_3.isChecked()):
            print("Seleccionaste: ", self.radioButton_3.text())
        else:
            print("ninguno")

    def leer_usuarios(self):
        self.tableWidget.setColumnCount(2) # poniendo 2 columnas
        self.tableWidget.setHorizontalHeaderLabels(("Nombre", "Password"))

        with open("usuarios.csv") as f:
            usuarios = f.readlines()

        inx = 0 #indice
        for usuario in usuarios:
            usuario = usuario.replace("\n", "")
            nombre,password = usuario.split(";") # sepaarandolo por ;
            self.tableWidget.insertRow(inx)
            self.tableWidget.setItem(inx,0,QTableWidgetItem(nombre))
            self.tableWidget.setItem(inx, 1, QTableWidgetItem(password))
            inx = inx+1



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
